Repository ZahraArshia/book-flight-backend, pull requests merged in 2022-07, with the labels that each got.

#13 User controller
  app/controllers/api/v1/users_controller.rb
  app/helpers/api/v1/users_helper.rb
  config/routes.rb
  test/controllers/api/v1/users_controller_test.rb
Labels: enhancement

#18 Set current user
  app/controllers/api/v1/reservations_controller.rb
  app/controllers/api/v1/users_controller.rb
  app/controllers/application_controller.rb
Labels: fixbug

#16 Adding controller & route for items (flights)
  Gemfile.lock
  app/controllers/api/v1/items_controller.rb
  config/routes.rb
Labels: enhancement

#20 Add endpoint for fetching each user items
  app/controllers/api/v1/items_controller.rb
  config/routes.rb
Labels: enhancement

#25 modify item controller
  app/controllers/api/v1/items_controller.rb
Labels: fixbug

#28 Delete item quick fix
  app/controllers/api/v1/items_controller.rb
  config/routes.rb
Labels: documentation, enhancement, fixbug

#29 Api documentation
  .rspec
  .rubocop.yml
  Gemfile
  Gemfile.lock
  spec/integration/authentications_spec.rb
  spec/integration/items_spec.rb
  spec/integration/reservations_spec.rb
  spec/integration/users_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
  swagger/v1/swagger.yaml
Labels: documentation
